export const data = [
  {
    _id: "670e85355a74d28e495aaf4e",
    firstName: "Ashwin",
    lastName: "Gorle",
    entryDetails: {
      currentQuarter: {
        clientEntries: 19,
        contactEntries: 2,
        registrationEntries: 0,
        tenderEntries: 0,
        mentionEntries: 6,
        leadEntries: 8,
        prospectEntries: 5,
        qualificationEntries: 50,
        followUpEntries: 2,
        proposalEntries: 12,
        closingEntries: 6,
        wonEntries: 2,
      },
      lastQuarter: {
        clientEntries: 9,
        contactEntries: 2,
        registrationEntries: 0,
        tenderEntries: 0,
        mentionEntries: 6,
        leadEntries: 1,
        prospectEntries: 5,
        qualificationEntries: 10,
        followUpEntries: 2,
        proposalEntries: 12,
        closingEntries: 6,
        wonEntries: 2,
      },
      last3rdQuarter: {
        clientEntries: 9,
        contactEntries: 2,
        registrationEntries: 11,
        tenderEntries: 0,
        mentionEntries: 6,
        leadEntries: 8,
        prospectEntries: 5,
        qualificationEntries: 50,
        followUpEntries: 2,
        proposalEntries: 12,
        closingEntries: 25,
        wonEntries: 2,
      },
      last4thQuarter: {
        clientEntries: 9,
        contactEntries: 2,
        registrationEntries: 0,
        tenderEntries: 0,
        mentionEntries: 6,
        leadEntries: 8,
        prospectEntries: 5,
        qualificationEntries: 50,
        followUpEntries: 2,
        proposalEntries: 12,
        closingEntries: 6,
        wonEntries: 2,
      },
      lastYear: {
        clientEntries: 9,
        contactEntries: 2,
        registrationEntries: 0,
        tenderEntries: 0,
        mentionEntries: 6,
        leadEntries: 8,
        prospectEntries: 5,
        qualificationEntries: 50,
        followUpEntries: 2,
        proposalEntries: 12,
        closingEntries: 6,
        wonEntries: 2,
      },
    },
  },
  {
    _id: "670e85355a74d28e495aaf4e",
    firstName: "Priyanshu",
    lastName: "Jaj",
    entryDetails: {
      currentQuarter: {
        clientEntries: 9,
        contactEntries: 12,
        registrationEntries: 0,
        tenderEntries: 0,
        mentionEntries: 6,
        leadEntries: 8,
        prospectEntries: 5,
        qualificationEntries: 50,
        followUpEntries: 2,
        proposalEntries: 12,
        closingEntries: 6,
        wonEntries: 2,
      },
      lastQuarter: {
        clientEntries: 9,
        contactEntries: 2,
        registrationEntries: 0,
        tenderEntries: 0,
        mentionEntries: 6,
        leadEntries: 1,
        prospectEntries: 5,
        qualificationEntries: 10,
        followUpEntries: 2,
        proposalEntries: 12,
        closingEntries: 6,
        wonEntries: 2,
      },
      last3rdQuarter: {
        clientEntries: 9,
        contactEntries: 2,
        registrationEntries: 11,
        tenderEntries: 0,
        mentionEntries: 6,
        leadEntries: 8,
        prospectEntries: 5,
        qualificationEntries: 50,
        followUpEntries: 2,
        proposalEntries: 12,
        closingEntries: 25,
        wonEntries: 2,
      },
      last4thQuarter: {
        clientEntries: 9,
        contactEntries: 2,
        registrationEntries: 0,
        tenderEntries: 0,
        mentionEntries: 6,
        leadEntries: 8,
        prospectEntries: 5,
        qualificationEntries: 50,
        followUpEntries: 2,
        proposalEntries: 12,
        closingEntries: 6,
        wonEntries: 2,
      },
      lastYear: {
        clientEntries: 9,
        contactEntries: 2,
        registrationEntries: 0,
        tenderEntries: 0,
        mentionEntries: 6,
        leadEntries: 8,
        prospectEntries: 5,
        qualificationEntries: 50,
        followUpEntries: 2,
        proposalEntries: 12,
        closingEntries: 6,
        wonEntries: 2,
      },
    },
  },
  {
    _id: "670e85355a74d28e495aaf4e",
    firstName: "Rohit",
    lastName: "Gupta",
    entryDetails: {
      currentQuarter: {
        clientEntries: 9,
        contactEntries: 12,
        registrationEntries: 0,
        tenderEntries: 0,
        mentionEntries: 6,
        leadEntries: 8,
        prospectEntries: 5,
        qualificationEntries: 50,
        followUpEntries: 2,
        proposalEntries: 12,
        closingEntries: 6,
        wonEntries: 2,
      },
      lastQuarter: {
        clientEntries: 9,
        contactEntries: 2,
        registrationEntries: 0,
        tenderEntries: 0,
        mentionEntries: 6,
        leadEntries: 1,
        prospectEntries: 5,
        qualificationEntries: 10,
        followUpEntries: 2,
        proposalEntries: 12,
        closingEntries: 6,
        wonEntries: 2,
      },
      last3rdQuarter: {
        clientEntries: 9,
        contactEntries: 2,
        registrationEntries: 11,
        tenderEntries: 0,
        mentionEntries: 6,
        leadEntries: 8,
        prospectEntries: 5,
        qualificationEntries: 50,
        followUpEntries: 2,
        proposalEntries: 12,
        closingEntries: 25,
        wonEntries: 2,
      },
      last4thQuarter: {
        clientEntries: 9,
        contactEntries: 2,
        registrationEntries: 0,
        tenderEntries: 0,
        mentionEntries: 6,
        leadEntries: 8,
        prospectEntries: 5,
        qualificationEntries: 50,
        followUpEntries: 2,
        proposalEntries: 12,
        closingEntries: 6,
        wonEntries: 2,
      },
      lastYear: {
        clientEntries: 9,
        contactEntries: 2,
        registrationEntries: 0,
        tenderEntries: 0,
        mentionEntries: 6,
        leadEntries: 8,
        prospectEntries: 5,
        qualificationEntries: 50,
        followUpEntries: 2,
        proposalEntries: 12,
        closingEntries: 6,
        wonEntries: 2,
      },
    },
  },
  {
    _id: "670e85355a74d28e495aaf4e",
    firstName: "Bablue",
    lastName: "Sharma",
    entryDetails: {
      currentQuarter: {
        clientEntries: 9,
        contactEntries: 12,
        registrationEntries: 0,
        tenderEntries: 0,
        mentionEntries: 6,
        leadEntries: 8,
        prospectEntries: 5,
        qualificationEntries: 50,
        followUpEntries: 2,
        proposalEntries: 12,
        closingEntries: 6,
        wonEntries: 2,
      },
      lastQuarter: {
        clientEntries: 9,
        contactEntries: 2,
        registrationEntries: 0,
        tenderEntries: 0,
        mentionEntries: 6,
        leadEntries: 1,
        prospectEntries: 5,
        qualificationEntries: 10,
        followUpEntries: 2,
        proposalEntries: 12,
        closingEntries: 6,
        wonEntries: 2,
      },
      last3rdQuarter: {
        clientEntries: 9,
        contactEntries: 2,
        registrationEntries: 11,
        tenderEntries: 0,
        mentionEntries: 6,
        leadEntries: 8,
        prospectEntries: 5,
        qualificationEntries: 50,
        followUpEntries: 2,
        proposalEntries: 12,
        closingEntries: 25,
        wonEntries: 2,
      },
      last4thQuarter: {
        clientEntries: 9,
        contactEntries: 2,
        registrationEntries: 0,
        tenderEntries: 0,
        mentionEntries: 6,
        leadEntries: 8,
        prospectEntries: 5,
        qualificationEntries: 50,
        followUpEntries: 2,
        proposalEntries: 12,
        closingEntries: 6,
        wonEntries: 2,
      },
      lastYear: {
        clientEntries: 9,
        contactEntries: 2,
        registrationEntries: 0,
        tenderEntries: 0,
        mentionEntries: 6,
        leadEntries: 8,
        prospectEntries: 5,
        qualificationEntries: 50,
        followUpEntries: 2,
        proposalEntries: 12,
        closingEntries: 6,
        wonEntries: 2,
      },
    },
  },
  {
    _id: "670e85355a74d28e495aaf4e",
    firstName: "Sawan",
    lastName: "Jaj",
    entryDetails: {
      currentQuarter: {
        clientEntries: 9,
        contactEntries: 12,
        registrationEntries: 0,
        tenderEntries: 0,
        mentionEntries: 6,
        leadEntries: 8,
        prospectEntries: 5,
        qualificationEntries: 50,
        followUpEntries: 2,
        proposalEntries: 12,
        closingEntries: 6,
        wonEntries: 2,
      },
      lastQuarter: {
        clientEntries: 9,
        contactEntries: 2,
        registrationEntries: 0,
        tenderEntries: 0,
        mentionEntries: 6,
        leadEntries: 1,
        prospectEntries: 5,
        qualificationEntries: 10,
        followUpEntries: 2,
        proposalEntries: 12,
        closingEntries: 6,
        wonEntries: 2,
      },
      last3rdQuarter: {
        clientEntries: 9,
        contactEntries: 2,
        registrationEntries: 11,
        tenderEntries: 0,
        mentionEntries: 6,
        leadEntries: 8,
        prospectEntries: 5,
        qualificationEntries: 50,
        followUpEntries: 2,
        proposalEntries: 12,
        closingEntries: 25,
        wonEntries: 2,
      },
      last4thQuarter: {
        clientEntries: 9,
        contactEntries: 2,
        registrationEntries: 0,
        tenderEntries: 0,
        mentionEntries: 6,
        leadEntries: 8,
        prospectEntries: 5,
        qualificationEntries: 50,
        followUpEntries: 2,
        proposalEntries: 12,
        closingEntries: 6,
        wonEntries: 2,
      },
      lastYear: {
        clientEntries: 9,
        contactEntries: 2,
        registrationEntries: 0,
        tenderEntries: 0,
        mentionEntries: 6,
        leadEntries: 8,
        prospectEntries: 5,
        qualificationEntries: 50,
        followUpEntries: 2,
        proposalEntries: 12,
        closingEntries: 6,
        wonEntries: 2,
      },
    },
  },
];

export const parameterToLabelMapLeft = {
  clientEntries: "Client",
  contactEntries: "Contact",
  registrationEntries: "Registration",
  tenderEntries: "Tender",
  mentionEntries: "Mention",
};

export const parameterToLabelMapRight = {
  leadEntries: "Lead",
  prospectEntries: "Prospect",
  qualificationEntries: "Qualification",
  followUpEntries: "Follow-Up",
  proposalEntries: "Proposal",
  closingEntries: "Closing",
};
