export const serverURL = "http://localhost:4321"
// export const serverURL = "https://crm-backend-liard.vercel.app"
// export const serverURL = "https://crm-backend-46sy1b39t-ashwin-gorles-projects.vercel.app"
// export const serverURL = "https://crm-backend-k0mi.onrender.com"
// export const serverURL = "https://crm-backend-git-ashwin-ashwin-gorles-projects.vercel.app"
